"""new one

Revision ID: 19ca5903d27c
Revises: d977ed636928
Create Date: 2026-05-17 00:44:04.620610

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '19ca5903d27c'
down_revision: Union[str, Sequence[str], None] = 'd977ed636928'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('uploaded_images',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('url', sa.String(length=1000), nullable=False),
    sa.Column('entity_type', sa.String(length=20), nullable=False),
    sa.Column('entity_id', sa.UUID(), nullable=True),
    sa.Column('ordering', sa.Integer(), nullable=False),
    sa.Column('created_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.Column('updated_at', sa.DateTime(timezone=True), server_default=sa.text('now()'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.add_column('sellers', sa.Column('is_deleted', sa.Boolean(), nullable=True))
    op.execute("UPDATE sellers SET is_deleted = FALSE")
    op.alter_column('sellers', 'is_deleted', nullable=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('sellers', 'is_deleted')
    op.drop_table('uploaded_images')
    # ### end Alembic commands ###
