"""add_invoice_accept_fields

Revision ID: 319219d0b078
Revises: 19ca5903d27c
Create Date: 2026-05-22 20:15:11.641827

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '319219d0b078'
down_revision: Union[str, Sequence[str], None] = '19ca5903d27c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('invoice_items', sa.Column('accepted_quantity', sa.Integer(), nullable=False))
    op.add_column('invoices', sa.Column('accepted_at', sa.DateTime(timezone=True), nullable=True))
    op.add_column('invoices', sa.Column('accepted_by', sa.UUID(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('invoices', 'accepted_by')
    op.drop_column('invoices', 'accepted_at')
    op.drop_column('invoice_items', 'accepted_quantity')
    # ### end Alembic commands ###
