"""ref

Revision ID: d977ed636928
Revises: b7c8d9e0f1a2
Create Date: 2026-05-11 23:45:46.239266

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'd977ed636928'
down_revision: Union[str, Sequence[str], None] = 'b7c8d9e0f1a2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('inbox_events')
    op.drop_index(op.f('ix_outbox_events_event_type'), table_name='outbox_events')
    op.drop_constraint(op.f('uq_outbox_events_idempotency_key'), 'outbox_events', type_='unique')
    op.create_index(op.f('ix_outbox_events_idempotency_key'), 'outbox_events', ['idempotency_key'], unique=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_outbox_events_idempotency_key'), table_name='outbox_events')
    op.create_unique_constraint(op.f('uq_outbox_events_idempotency_key'), 'outbox_events', ['idempotency_key'], postgresql_nulls_not_distinct=False)
    op.create_index(op.f('ix_outbox_events_event_type'), 'outbox_events', ['event_type'], unique=False)
    op.create_table('inbox_events',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('idempotency_key', sa.VARCHAR(length=100), autoincrement=False, nullable=False),
    sa.Column('event_type', sa.VARCHAR(length=50), autoincrement=False, nullable=False),
    sa.Column('aggregate_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('payload', sa.TEXT(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), server_default=sa.text('now()'), autoincrement=False, nullable=False),
    sa.PrimaryKeyConstraint('id', name=op.f('inbox_events_pkey'))
    )
    # ### end Alembic commands ###
